{% set name = "napari-zulip" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-zulip-{{ version }}.tar.gz
  sha256: 56a54ced83384f9942b02eb077f1a85131e144463a6a98533248b5e8a5a56fad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - magicgui
    - qtpy
    - zulip

test:
  imports:
    - napari_zulip
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kephale/napari-zulip
  summary: A simple plugin for interacting with Zulip from napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
